# Hexo Configuration
## Docs: https://hexo.io/docs/deployment.html
## Source: https://github.com/hexojs/hexo

# Site
title: A-Frame
subtitle: Building Blocks for the VR Web
description: "Building Blocks for the VR Web"
author: MozVR
email: aframe@mozilla.com
language:
robots: all
blog_title: Blog

# Color for `<meta name="theme-color">`
## https://html.spec.whatwg.org/multipage/semantics.html#meta-theme-color
## https://developers.google.com/web/fundamentals/design-and-ui/browser-customization/theme-color
theme_color: black

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://aframe.io/
root: /
permalink: blog/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
force_https: true

# Directory
source_dir: src
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: page
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: false
highlight:
  enable: true
  line_number: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 0
category: 0
tag: 0

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
server:
  port: 4000
  log: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: aframe
exclude_generator:
- index

# Feed
## Plugin https://github.com/hexojs/hexo-generator-feed
feed:
  type: rss2
  path: feed.xml
  limit: 15
  hub:

# Markdown
## https://github.com/chjj/marked
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: false
  smartLists: true
  smartypants: true
  modifyAnchors: 1  # Lowercased anchors.

# Browsersync
## Repo: https://github.com/hexojs/hexo-browsersync
## Options: https://www.browsersync.io/docs/options/
browsersync:
  notify: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:aframevr/aframevr.github.io.git

disqus_shortname:
twitter:
  username: aframevr
  url: https://twitter.com/aframevr/
google_analytics: UA-24056643-4
fb_app_id: 1535794316743373

github:
  aframe:
    username: aframevr
    repo: aframe
    url: https://github.com/aframevr/aframe/
  aframe_site:
    username: aframevr
    repo: aframe-site
    url: https://github.com/aframevr/aframe-site/

slack:
  aframe:
    signup_url: https://aframevr-slack.herokuapp.com

aframe_version: 0.2.0

# Single-Page App
spa: false
